<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion><!-- -->

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.14</version>
    <relativePath /> <!-- lookup parent from repository -->
  </parent>

  <groupId>se.skltp.tak</groupId>
  <artifactId>kat</artifactId>
  <version>1.5.1</version>
  <packaging>pom</packaging>

  <name>kat</name>
  <description>SKLTP KAT</description>

  <modules>
    <module>kat-tak-mock</module>
    <module>kat-application</module>
    <module>report</module>
  </modules>

  <scm>
    <url>https://github.com/skltp/kat.git</url>
    <connection>scm:git:https://github.com:443/skltp/kat.git</connection>
    <developerConnection>scm:git:https://github.com:443/skltp/kat.git
    </developerConnection>
    <tag>HEAD</tag>
  </scm>

  <properties>
    <!-- TODO: REGULARLY CHECK UPDATES FOR DEPS -#- DEPENDENCIES CHECKED: MAY 2026. -->

    <!-- Core Dependencies and Properties-->
    <java.version>17</java.version>
    <maven.compiler.release>17</maven.compiler.release>

    <spring.boot-version>3.5.14</spring.boot-version> <!-- APR 2026 -->
    <!-- Our internal TAK and TAK-Cache. Used in application child module. -->
    <tak.version>4.4.1</tak.version> <!-- MAY 2026 -->
    <takcache.version>3.0.5</takcache.version> <!-- MAY 2026 -->
    <cxf.version>4.1.6</cxf.version> <!-- MAY 2026 - 4.1.x is aligned to Spring Boot 3, and Jakarta EE10 - 4.2.x exists but is aligned to Spring Boot 4. -->

    <!-- Supporting Deps -->
    <jaxws.version>4.0.4</jaxws.version> <!-- MAR 2026 -->
    <log4j2.version>2.25.4</log4j2.version> <!-- MAR 2026 -->
    <jakarta.activation.version>2.1.4</jakarta.activation.version> <!-- SEP 2024 -->

    <!-- Dev and Monitoring -->
    <ecs-logging-java.version>1.7.0</ecs-logging-java.version> <!-- APR 2025. Latest as of APR 2026. -->
    <jacoco.plugin.version>0.8.14</jacoco.plugin.version> <!-- OCT 2025. Latest as of APR 2026. -->
    <maven.deploy.skip>true</maven.deploy.skip>

    <!-- Project details -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- Override Log4j2 version to fix CVEs.
            TODO: Remove this override once Spring Boot or Camel is in phase again. -->
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-bom</artifactId>
        <version>${log4j2.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot-version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
