apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: kat
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kat-application
  template:
    metadata:
      annotations:
      labels:
        app: kat-application
        app.kubernetes.io/name: kat-application
        elasticGrokFilter: {{ .Values.deployment.elasticGrokFilter }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: kat-application
          image: "{{ .Values.repository }}kat-application:{{ .Values.container.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - containerPort: 8082
              protocol: TCP
              name: kat
          # Injection of startup, liveness, and/or readiness probes below.
          {{- .Values.probes | toYaml | nindent 10 }}

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            {{- range $.Values.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}