apiVersion: v1
kind: ConfigMap
metadata:
  name: kat-configmap-default
data:
  # Webserver general settings
  SERVER_PORT: "{{ .Values.server.port }}"
  SERVER_SHUTDOWN: "{{ .Values.server.shutdown }}"

  # Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "{{ .Values.management.endpointsWebExposureInclude | join "," }}"
  MANAGEMENT_SERVER_PORT: "{{ .Values.management.serverPort }}"

  # Configuration for tomcat accesslog
  SERVER_TOMCAT_ACCESSLOG_BUFFERED: "{{ .Values.server.tomcat.accesslog.buffered }}"
  SERVER_TOMCAT_ACCESSLOG_DIRECTORY: "{{ tpl .Values.server.tomcat.accesslog.directory . }}"
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "{{ .Values.server.tomcat.accesslog.enabled }}"
  SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT: "{{ .Values.server.tomcat.accesslog.fileDateFormat }}"
  SERVER_TOMCAT_ACCESSLOG_PATTERN: "{{ .Values.server.tomcat.accesslog.pattern }}"
  SERVER_TOMCAT_ACCESSLOG_PREFIX: "{{ .Values.server.tomcat.accesslog.prefix }}"
  SERVER_TOMCAT_ACCESSLOG_RENAME_ON_ROTATE: "{{ .Values.server.tomcat.accesslog.renameOnRotate }}"
  SERVER_TOMCAT_ACCESSLOG_REQUEST_ATTRIBUTES_ENABLED: "{{ .Values.server.tomcat.accesslog.requestAttributesEnabled }}"
  SERVER_TOMCAT_ACCESSLOG_ROTATE: "{{ .Values.server.tomcat.accesslog.rotate }}"
  SERVER_TOMCAT_ACCESSLOG_SUFFIX: "{{ .Values.server.tomcat.accesslog.suffix }}"
  SERVER_TOMCAT_ACCESSLOG_MAX_DAYS: "{{ .Values.server.tomcat.accesslog.maxDays }}"

  #----------------------  
  # KAT configuration
  #----------------------

  # Basepath to webservices
  CXF_PATH: "{{ .Values.cxf.path }}"

  # KAT - subpaths to webservices
  KAT_GETSUPPORTEDSERVICECONTRACTS_V2_PATH: "{{ .Values.kat.getSupportedServiceContractsV2Path }}"
  KAT_GETLOGICALADDRESSEESBYSERVICECONTRACT_V2_PATH: "{{ .Values.kat.getLogicalAddresseesByServiceContractV2Path }}"

  # KAT - Path to REST resetcache service
  KAT_RESETCACHE_PATH: "{{ .Values.kat.resetcachePath }}"

  # TAK configuration
  TAKCACHE_USE_BEHORIGHET_CACHE: "{{ .Values.takcache.useBehorighetCache }}"
  TAKCACHE_USE_VAGVAL_CACHE: "{{ .Values.takcache.useVagvalCache }}"
  TAKCACHE_PERSISTENT_FILE_NAME: "{{ .Values.takcache.persistentFileName }}"
  TAKCACHE_ENDPOINT_ADDRESS: "{{ .Values.takcache.endpointAddress }}"
  TAKCACHE_HEADER_USER_AGENT: "{{ .Values.takcache.headerUserAgent }}"

  # LOG4J configuration
  LOG4J_APPENDER: "{{ .Values.log4j.appender }}"
