apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vip.name }}
spec:
  selector:
    app.kubernetes.io/name: kat-application
  type: ClusterIP
  ports:
    - port: {{ .Values.vip.port }}
      targetPort: 8082
      protocol: TCP
      name: http
status:
  loadBalancer: {}
