namespace: ntjp

deployment:
  name: kat
  replicaCount: 1

container:
  image:
    name: kat-application
    pullPolicy: Always

service:
  name: kat
  type: ClusterIP
  port: 8082

environment:
  variables:
    _default_config_maps:
      - kat-configmap-default
      - kat-configmap-log4j2
    config_maps:
      # Override to supply your own maps.
    secrets:
      # Override to supply your own secrets.
