repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  elasticGrokFilter: camel
  resources: #{} # The no-op curly-braces can optionally replace below sub-resources.
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 512Mi

container:
  image:
    tag: # Override to supply another image tag to run
    pullPolicy: Always

# Environment-specific backwards-compatible service name
vip:
  name: default-vp-vip

environment:
  variables:
    _default_config_maps:
      - kat-configmap-default
    config_maps:
      # Override to supply your own maps.
    secrets:
      # Override to supply your own secrets.